# Generated by Django 4.2 on 2025-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="레시피 제목")),
                ("ingredients", models.TextField(verbose_name="재료")),
                ("instructions", models.TextField(verbose_name="조리순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "레시피",
                "verbose_name_plural": "레시피 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
