SELECT
    FISH_COUNT,
    FISH_NAME
FROM (
        SELECT
            FISH_TYPE,
            COUNT(ID) AS FISH_COUNT
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) G
    LEFT JOIN FISH_NAME_INFO
    USING (FISH_TYPE)
ORDER BY FISH_COUNT DESC;