WITH QuarterData AS (
    SELECT 
        CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER,
        QUARTER(DIFFERENTIATION_DATE) AS QUARTER_NUM
    FROM 
        ECOLI_DATA
)
SELECT 
    QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM 
    QuarterData
GROUP BY 
    QUARTER, QUARTER_NUM
ORDER BY 
    QUARTER_NUM;