WITH YEARLY_SCORE AS (
    SELECT 
        EMP_NO,
        SUM(SCORE) as SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT 
    ys.SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM YEARLY_SCORE ys
JOIN HR_EMPLOYEES e ON ys.EMP_NO = e.EMP_NO
WHERE ys.SCORE = (
    SELECT MAX(SCORE)
    FROM YEARLY_SCORE
)
ORDER BY e.EMP_NO;