SELECT 
    bk.CATEGORY AS CATEGORY, 
    SUM(bs.SALES) AS TOTAL_SALES
FROM 
    BOOK AS bk
JOIN 
    BOOK_SALES AS bs
ON 
    bk.BOOK_ID = bs.BOOK_ID
WHERE 
    bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 
    bk.CATEGORY
ORDER BY 
    bk.CATEGORY;